//firebase_options.dart
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0QJL-6P8Jxw-cgzSg3cJ83wUKH7PjXBs',
    appId: '1:127718735081:web:0aed3f3755a5ab3f9cc478',
    messagingSenderId: '127718735081',
    projectId: 'odaksinif',
    authDomain: 'odaksinif.firebaseapp.com',
    storageBucket: 'odaksinif.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMtISZ_WJbK9QeslZIUNYjcPVLlebBkHE',
    appId: '1:127718735081:android:eda859649333a0099cc478',
    messagingSenderId: '127718735081',
    projectId: 'odaksinif',
    storageBucket: 'odaksinif.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGDeXPC68J4pjHB1pLnandybx5tHiIivk',
    appId: '1:127718735081:ios:6575b05c8b53b3f19cc478',
    messagingSenderId: '127718735081',
    projectId: 'odaksinif',
    storageBucket: 'odaksinif.firebasestorage.app',
    iosBundleId: 'com.example.yazilimmuhendislgiproje',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGDeXPC68J4pjHB1pLnandybx5tHiIivk',
    appId: '1:127718735081:ios:6575b05c8b53b3f19cc478',
    messagingSenderId: '127718735081',
    projectId: 'odaksinif',
    storageBucket: 'odaksinif.firebasestorage.app',
    iosBundleId: 'com.example.yazilimmuhendislgiproje',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0QJL-6P8Jxw-cgzSg3cJ83wUKH7PjXBs',
    appId: '1:127718735081:web:71386371928f50f89cc478',
    messagingSenderId: '127718735081',
    projectId: 'odaksinif',
    authDomain: 'odaksinif.firebaseapp.com',
    storageBucket: 'odaksinif.firebasestorage.app',
  );
}
